### ISSUE TITLE
Make reader macros ('`~) searchable 

### ISSUE THREAD

**Issue by vibl** [clojure-grimoire/grimoire#222]
When I type an apostrophe:
```
'
```
or a backtick:
```
`
```
or a tilde:
```
~
```
in the search bar, no result is shown.

These are typically the kind of characters Grimoire would be very useful for because we can't google them.

Thank you for Grimoire!

Vianney

**Comment by arrdem** [comment]
Awesome idea! I've been meaning to overhaul the front page and search for a while and I think this'd be totally doable. I'll circle back to this after exams.

**Comment by arrdem** [comment]
These are now totally doable with the new `0.5.0` search infrastructure, the only question is what should these characters link to as search results. On the one hand, none of Clojure's docstrings really talk about the reader (not even stuff like `read-string` or `read`) so maybe it's best to link to [the official reader reference](http://clojure.org/reference/reader), but that page suffers from the usual criticism of being written by and for an expert rather than being fully introductory which suggests that Grimoire should feature a reader page somewhere/somehow.
