### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by backerman** [clojure-grimoire/grimoire#262]
Expired: Monday, May 15, 2017 at 02:20:00 Eastern Daylight Time

**Comment by arrdem** [comment]
Argh. Thanks for the heads up.

**Comment by arrdem** [comment]
https://twitter.com/arrdem/status/869024909179191296

Okay. Much fing about later, this is fixed.

1. Nginx wasn't running logrotate, disk was full. Nothing was working.
2. Nginx was configured to read SSL certs from the wrong directory.
3. The SSL cert updater didn't even have a directory to write to.
4. An OS update meant that I had to port the Grimoire service from upstart to systemd.
5. Did I mention I did an OS update?

All should be well now. Got moved to systemd, got everything working happily again (for now). Got the various cronjobs set up to send me status emails instead of being silent.

Really need to do something about the fact that my ping "up" alerts "succeed" even when the SSL certs go bad.

**Comment by arrdem** [comment]
Total incident time something near 14h. Apologies for the interruption :cry:

**Comment by backerman** [comment]
And now it's 500... eek.

**Comment by arrdem** [comment]
Blerg

**Comment by arrdem** [comment]
Okay. So this time Grimoire died overnight due to a memory leak and systemd didn't restart the service correctly because the "do a git checkout" part of the script was refusing to pull master down due to local changes I left behind.
