### ISSUE TITLE
Links in the Source to other functions

### ISSUE THREAD

**Issue by halgari** [clojure-grimoire/grimoire#41]
Massive feature request here, but I'd love to see every function call inside the source listings to be a hyper-link to that function. Not exactly sure how we would go about adding this (tools.analyzer?). But it'd be really nice to see.

**Comment by arrdem** [comment]
A poor man's version of this, since the overwhelming majority of source code on the site is example code, would be to simply recognize uses of `clojure.core` defs and preprocess occurances of core symbols to generate links to their documentation. This should work since examples are by a large REPL sessions and most examples & documentation on the site are written about `clojure.core`.

The real answer is and remains a TANAL based highlighter. Since we now have weavejester/cljfmt building a real HTML "pretty printer" may be something that could be bolted on to that project.

**Comment by arrdem** [comment]
Closing because Grimoire's goal is to be a documentation & articles reference, not a code browser.
